# In The Name Of God
# ========================================
# [] File Name : Makefile
#
# [] Creation Date : 15-01-2016
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================

.PHONY: all
all: roadmap

roadmap: adjcalc.sty adjustbox.sty collectbox.sty minted.sty trimclip.sty aut.sty roadmap.tex
	xelatex -shell-escape roadmap.tex
