# In The Name Of God
# ========================================
# [] File Name : Makefile
#
# [] Creation Date : 15-01-2016
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================

.PHONY: all
all: kaa

kaa: adjcalc.sty adjustbox.sty collectbox.sty trimclip.sty aut.sty kaa.tex
	xelatex -shell-escape -8bit kaa.tex
